title: Witness My Depths
description: A collection of poems
baseurl: "/witness-my-depths-web"
url: "https://qubitty.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  poems:
    output: true
    permalink: /:collection/:name/ 