name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches: [ main ]
  schedule:
    # Run daily at midnight to update poems
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      
      - name: Fetch poems
        run: |
          mkdir -p _poems
          bundle install
          ruby scripts/fetch_poems.rb
      
      - name: Build site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site 