name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches: [ main ]
  schedule:
    # Run daily at midnight to update poems
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false # Disable bundler-cache to handle it manually
      
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      
      - name: Fetch poems
        run: |
          mkdir -p _poems
          ruby scripts/fetch_poems.rb
      
      - name: Show Jekyll version and environment
        run: |
          bundle exec jekyll --version
          bundle info jekyll
          bundle info github-pages
          echo "JEKYLL_ENV=$JEKYLL_ENV"
      
      - name: Build site
        run: |
          bundle exec jekyll build --trace
        env:
          JEKYLL_ENV: production
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          full_commit_message: 'Deploy Jekyll site to GitHub Pages' 